# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  ssowebapp:
    image: 463503197761.dkr.ecr.eu-west-1.amazonaws.com/ssowebapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
