apiVersion: apps/v1
kind: Deployment
metadata:
    name: ssowebapp-deploy
    labels:
        app: ssowebapp-app
    annotations:
spec:
    replicas: 2
    selector:
        matchLabels:
            app: ssowebapp-app
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                app: ssowebapp-app
        spec:
            containers:
            - name: ssowebapp-app
              image: thesolutionarchitect/ssowebapp:1.0.0
              imagePullPolicy: Always
              ports:
              - containerPort: 4000
              resources:
                requests:
                    memory: "64Mi" 
                    cpu: "50m"
                limits:
                    memory: "256Mi"
                    cpu: "500m"
