apiVersion: v1
kind: Service
metadata:
    name: ssowebappservice
spec:
    type: LoadBalancer
    selector:
        app: ssowebapp-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
